version: "3.4"
services:

  ladoc: &ladoc
    build:
      context: .
    ports:
      - "1400:1400"
    volumes: 
      - ./:/docs/docs
      - /tmp/cachedir:/tmp/cachedir
      - /tmp/site:/docs/site

  ladoc-build:
    <<: *ladoc
    command: "build --clean"


 