version: "3.4"
services:

  docs: &docs
    image: ghcr.io/lasssim/docs:latest
    ports:
      - "9980:9980"
    volumes: 
      - ./:/docs/docs
      - /tmp/cachedir:/tmp/cachedir
      - /tmp/site:/docs/site

  docs-build:
    <<: *docs
    command: "build --clean"


 