version: "3.4"
services:

  ladoc: &ladocs
    image: ghcr.io/lasssim/docs:latest
    ports:
      - "1400:1400"
    volumes: 
      - ./:/docs/docs
      - /tmp/cachedir:/tmp/cachedir
      - /tmp/site:/docs/site

  ladoc-build:
    <<: *ladocs
    command: "build --clean"


 