name: Create and publish Docker images

on:
  push:
    branches: ['main']
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_BASE: ${{ github.repository }}-base

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Dockerfile.base is a shared base image for all other images
      - name: Check if Dockerfile.base was changed
        id: check_file
        run: |
          echo "::set-output name=modified::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^Dockerfile.base$' || echo false)"
        shell: bash
      
      - name: Extract metadata (tags, labels) for Docker base image
        id: meta_base
        if: steps.check_file.outputs.modified == 'Dockerfile.base'
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}

      - name: Build and push Docker base image
        uses: docker/build-push-action@v2
        if: steps.check_file.outputs.modified == 'Dockerfile.base'
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: ${{ steps.meta_base.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}

      # Actual image
      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}