site_name: !ENV [SITE_NAME, "TODO: Change SITE_NAME env variable"]

docs_dir: docs/

theme:
  custom_dir: 'theme'
  name: material
  logo: !ENV [LOGO, assets/images/logo.png]
  favicon: !ENV [FAVICON, assets/images/favicon.png]
  static_templates:
    - redoc.html
  palette:
    primary: 'black'
repo_url: !ENV [REPO_URL, https://change-repo-url-env-var/me] 
edit_uri: !ENV [EDIT_URI, edit/main]


markdown_extensions:
  plantuml_markdown:
    format: svg
    cachedir: /tmp/cachedir
  admonition:
  #lightgallery:
  attr_list:
  pymdownx.highlight:
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.superfences:
  fancyboxmd:

plugins:
  awesome-pages:
    collapse_single_pages: true
  macros:
    module_name: mkdocs_macros
  mkdocs-simple-hooks:
    hooks:
      on_files: "ladoc_hooks:add_hidden_files"
      on_pre_build: "ladoc_hooks:set_build_time_env_var"
  mkdocs-video: {}
  exclude:
    glob:
      - node_modules/*
      - tmp/*

copyright: !ENV [COPYRIGHT, "TODO: Change COPYRIGHT env variable"]

extra_css:
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js