site_name: !ENV [SITE_NAME, "TODO: Change SITE_NAME env variable"]

docs_dir: docs/

theme:
  custom_dir: 'theme'
  name: material
  logo: !ENV [LOGO, assets/images/logo.png]
  favicon: !ENV [FAVICON, assets/images/favicon.png]
  static_templates:
    - redoc.html
  palette:
    primary: 'black'
repo_url: !ENV [REPO_URL, https://change-repo-url-env-var/me] 
edit_uri: !ENV [EDIT_URI, edit/main]


markdown_extensions:
  - plantuml_markdown:
      format: svg
      cachedir: /tmp/cachedir
  - codehilite
  - admonition
  - lightgallery
  - attr_list

plugins:
  - awesome-pages:
      collapse_single_pages: true
  - macros:
      module_name: mkdocs_macros
  - inline-svg
  - mkdocs-simple-hooks:
      hooks:
        on_files: "ladoc_hooks:add_hidden_files"
  - mkdocs-video
  - exclude:
      glob: 
        - node_modules/*

copyright: !ENV [COPYRIGHT, "TODO: Change COPYRIGHT env variable"]
